#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Console\Crawler\CrawlerCommand;
use Symfony\Component\Console\Application;

$app = new Application();
$app->add(new CrawlerCommand());
$app->run();